### ISSUE TITLE
error: The read operation timed out

### ISSUE THREAD

**Issue by LumaCong** [codezjx/netease-cloud-music-dl#2]
Installed d:\program files\python\python35\lib\site-packages\netease_cloud_music
_dl-0.2.0-py3.5.egg
Processing dependencies for netease-cloud-music-dl==0.2.0
Searching for pycrypto>=2.6.1
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/60/db/645aa9af249f059cc3a368b118de3
3889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf516
1a0d5d7eda
error: The read operation timed out

**Comment by codezjx** [comment]
pip的默认源都是非常慢的，超时很常见啦。
建议通过`pip install pycrypto==2.6.1`重新安装指定的依赖包。
如果还是会超时，可以通过`-i, --index-url <url>`参数来修改默认源。
例如，下面用的是豆瓣的源：
`pip install pycrypto==2.6.1 -i https://pypi.douban.com/simple`
