### ISSUE TITLE
playlist只能下载第一首？

### ISSUE THREAD

**Issue by kiolygenius** [codezjx/netease-cloud-music-dl#22]
ncm -p 701612700
只能下到求佛一首

**Comment by gaozhao1989** [comment]
这个接口只能获取最新添加的一个，所以只下载了一首
'http://music.163.com/api/playlist/detail?id={}'
应使用这个接口
'http://music.163.com/weapi/v3/playlist/detail?csrf_token='

不靠谱的方案：
修改api.py
`    def get_playlist_songs(self, playlist_id):
        """
        Get a public playlist all songs
        :param playlist_id:
        :return:
        """
        url = 'http://music.163.com/weapi/v3/playlist/detail?csrf_token='
        csrf = ''
        params = {'id': playlist_id, 'offset': 0, 'total': True,
                  'limit': 1000, 'n': 1000, 'csrf_token': csrf}
        result = self.post_request(url, params)
        song_ids = [song['id'] for song in result['playlist']['tracks']]
        return song_ids, result['playlist']['name']`

修改start.py
`def download_playlist_songs(playlist_id):
    song_ids, playlist_name = api.get_playlist_songs(playlist_id)
    songs = [api.get_song(song_id) for song_id in song_ids]
    *****`

**Comment by gaozhao1989** [comment]
playlist应使用接口
http://music.163.com/weapi/v3/playlist/detail?csrf_token=
可自行替换解决
