### ISSUE TITLE
能支持会员吗？

### ISSUE THREAD

**Issue by sbw983** [codezjx/netease-cloud-music-dl#25]
RT

冲了会员，就是为了能下无损的flac去的

**Comment by beterhans** [comment]
估计楼上可以把会员账号贡献出来 才能开发啊哈哈
不过 无损的 flac 是真 flac 吗 不是 320 mp3 转化的吗？

**Comment by codezjx** [comment]
@sbw983 @beterhans 这个项目是给没有会员的人用的哈~  有会员的自己用客户端下不就好了吗？
