### ISSUE TITLE
mac下使用没有找到下载的歌曲在哪里

### ISSUE THREAD

**Issue by cx4** [codezjx/netease-cloud-music-dl#27]
显示下载成功的log
但是没有找到下载目录在哪里，也没有找到配置的ini文件。

**Comment by codezjx** [comment]
@cx4 配置文件在在用户目录下自动生成，路径如下，下载目录也在这个配置文件里面指定，建议仔细看看`README`：

`/Users/你的用户名/.ncm/ncm.ini`

**Comment by cx4** [comment]
好的 谢谢。找到了，默认是隐藏状态。
