### ISSUE TITLE
在下载有些歌曲的专辑图的时候会stacktrace

### ISSUE THREAD

**Issue by Apache553** [codezjx/netease-cloud-music-dl#33]
比如说 https://music.163.com/#/song?id=611923 这一首
在下载专辑图的时候会出现异常 blurPicurl 是 None
然后整个过程中断

**Comment by codezjx** [comment]
服务器返回json结果为：http://music.163.com/api/song/detail/?ids=[611923]
`blurPicUrl`返回的确为`None`，惨淡淡，这个时候尝试获取`picUrl `

@Apache553 非常感谢反馈此问题~
