### ISSUE TITLE
有copyright的下载不了

### ISSUE THREAD

**Issue by kennethshuai** [codezjx/netease-cloud-music-dl#38]
NCM，有copyright的下载不了。
以前GIT有个netease-dl，它可以绕过copyright，但是netease-dl无人维护，最近netease music可能是升级了API等，netease-dl这套完全不能用了。

**Comment by chenjunyu19** [comment]
> NCM，有copyright的下载不了。
> 以前GIT有个netease-dl，它可以绕过copyright，但是netease-dl无人维护，最近netease music可能是升级了API等，netease-dl这套完全不能用了。

关于 `netease-dl` 的问题了解一下 <https://github.com/ziwenxie/netease-dl/issues/32>

**Comment by codezjx** [comment]
是滴呀，有copyright的下载不了。
[netease-dl](https://github.com/ziwenxie/netease-dl)也是不支持的呀，当初有部分代码就是参考这个项目的呀~  T_T~
