### ISSUE TITLE
-bash: ncm: command not found

### ISSUE THREAD

**Issue by wanglaihuai** [codezjx/netease-cloud-music-dl#4]
安装完了，提示ncm找不到？
Finished processing dependencies for netease-cloud-music-dl==0.2.0
bogon:~ huai$ ncm
-bash: ncm: command not found

**Comment by codezjx** [comment]
当模块安装完成后，会把打包好的egg包拷贝至site-packages下，并在bin目录生成ncm的入口。
控制台`$ echo $PATH`打印环境变量，看看是否包含python的bin路径，我本机是下面这个：
> /Library/Frameworks/Python.framework/Versions/3.6/bin

如果没有上面的bin目录，要在`~/.bash_profile`里面添加环境变量哦亲

**Comment by wanglaihuai** [comment]
好的，我再试试。多谢大神。

**Comment by wanglaihuai** [comment]
好了，如果用pyenv环境多版本的python，需要把ncm文件夹拷贝到 /Users/***/.pyenv/versions/3.6.1/lib/python3.6/site-packages。
