### ISSUE TITLE
 高音质/标准音质/低音质，下载，是否有效？

### ISSUE THREAD

**Issue by kennethshuai** [codezjx/netease-cloud-music-dl#41]
https://github.com/mrlovables/Netease
这个项目中有 高音质/标准音质/低音质的区分下载，该方法是否有效？能否借鉴？

**Comment by MountainColdWay** [comment]
可以自己手动改，硬件跟不上还不是没用

**Comment by codezjx** [comment]
ncm已经默认设置了320k高音质下载，但是不是所有歌曲都提供320k，如果没有，网易云会返回降级音质的mp3文件。具体解释见#40
