### ISSUE TITLE
请求支持 FLAC 文件

### ISSUE THREAD

**Issue by LynMoe** [codezjx/netease-cloud-music-dl#44]
现在的接口貌似可以下载到 FLAC 的歌曲了，为啥不支持 FLAC 呢 (不过转了一圈要给 FLAC 加封面貌似有点麻烦就是了

**Comment by LynMoe** [comment]
需求有点特殊，fork 自己改了，感谢

**Comment by codezjx** [comment]
@LoliLin 如果改完了可以给我提个PR哈:)

**Comment by LynMoe** [comment]
https://github.com/LoliLin/CloudMan
related 啦
