### ISSUE TITLE
Some music can't be downloaded

### ISSUE THREAD

**Issue by COMMANDERWONG** [codezjx/netease-cloud-music-dl#52]
when using the ncm -a album download, some songs can't be downloaded completly.
![Capture](https://user-images.githubusercontent.com/37576365/80140897-39117980-85db-11ea-93ec-8d82538d4dc0.PNG)

**Comment by codezjx** [comment]
@COMMANDERWONG Maybe network issue? Everything works fine for me.
![1589357256733](https://user-images.githubusercontent.com/9532087/81788204-be31e380-9534-11ea-8a73-fe49533ba9de.jpg)
