### ISSUE TITLE
Only download first ten songs from a playlist?

### ISSUE THREAD

**Issue by SDhuangao** [codezjx/netease-cloud-music-dl#55]
不知道是歌单的处理方式变了还是怎么回事,可以下载热门50首,但是只要是歌单只能下载前10首. 之前几个月还是正常使用,换了新电脑后在python 3.9下就是这样了
![image](https://user-images.githubusercontent.com/30566162/106185212-7c89bb80-61dd-11eb-9705-c10e94c465b7.png)

**Comment by SDhuangao** [comment]
应该是网易云歌单的API改了，歌单一次只能下载前10首歌。但是requests好像能获取全部的歌单信息？

**Comment by SDhuangao** [comment]
修改了api接口等，已修复。

**Comment by codezjx** [comment]
@SDhuangao 感谢提醒，旧的api只能获取到10首，修改为新的v6 api。
