### ISSUE TITLE
下载歌单时,下载6首后停止下载

### ISSUE THREAD

**Issue by josedelinux** [codezjx/netease-cloud-music-dl#56]
输出如下
<pre><code>
jose@jose:~/utils/ncm/netease-cloud-music-dl$ ncm -p https://music.163.com/#/playlist?id=8729926516
1: In Case You Didn't Know
Mp3 file already download: Brett Young - In Case You Didn't Know.mp3
2: You Belong With Me
Mp3 file already download: Taylor Swift - You Belong With Me.mp3
3: When It Rains It Pours
Mp3 file already download: Luke Combs - When It Rains It Pours.mp3
4: Nobody But You (Duet with Gwen Stefani) [Live]
Mp3 file already download: Blake Shelton - Nobody But You (Duet with Gwen Stefani) [Live].mp3
5: Heaven
Mp3 file already download: Kane Brown - Heaven.mp3
6: Even Though I'm Leaving
Mp3 file already download: Luke Combs - Even Though I'm Leaving.mp3
jose@jose:~/utils/ncm/netease-cloud-music-dl$
</code></pre>

**Comment by codezjx** [comment]
@josedelinux 已修复，旧的api只能获取到10首，修改为新的v6 api。
