### ISSUE TITLE
实测下载的码率都是128的，不是320的，有没有办法能下载到320码率或者无损的呢？

### ISSUE THREAD

**Issue by liuzhenwubigboss** [codezjx/netease-cloud-music-dl#68]
<img width="1218" alt="image" src="https://github.com/codezjx/netease-cloud-music-dl/assets/31624973/5b8f7c59-d7ad-4909-9bb9-fbd2f7f653bb">

**Comment by codezjx** [comment]
@liuzhenwubigboss 无损下载不了的，目前码率默认设置320，没有的话就会回退128，估计猪场下架了320的源，以前是可以下的。详见代码：https://github.com/codezjx/netease-cloud-music-dl/blob/master/ncm/api.py#L91

**Comment by liuzhenwubigboss** [comment]
ok，谢谢
